db:
    image: postgres:9.4
    environment:
        - POSTGRES_PASSWORD=mysecretpassword
        - POSTGRES_USER=master
    #ports:
    #    - "3306:3306"
web:
    image: php:5.6-apache
    links:
        - db
    ports:
        - "80:80"
    volumes:
        - ../web:/var/www/html