db:
    image: postgres:9.4
    environment:
        - POSTGRES_PASSWORD=mysecretpassword
        - POSTGRES_USER=master
    ports:
        - "5432:5432"
web:
    build: .
    links:
        - db
    ports:
        - "80:80"
    volumes:
        - ../api/:/app
    working_dir: "/app"