language: node_js
node_js:
  - "0.12.2"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g grunt-cli karma bower
  - cd web
  - npm install
  - bower install
  - cd ..

script:
  - cd web; grunt

